#!/usr/bin/env python

import cmdparse
import halng.commands
import logging
import sys

parser = cmdparse.CommandParser()
parser.add_option("", "--debug", action="store_true",
                  help="enable debugging output")

parser.add_commands(halng.commands)

if __name__ == "__main__":
    (command, options, args) = parser.parse_args()

    formatter = logging.Formatter("%(levelname)s: %(message)s")
    console = logging.StreamHandler()
    console.setFormatter(formatter)
    logging.root.addHandler(console)

    if options.debug:
        logging.root.setLevel(logging.DEBUG)
    else:
        logging.root.setLevel(logging.INFO)

    if command is None:
        parser.print_help()
        sys.exit(1)

    try:
        command.run(options, args)
    except KeyboardInterrupt:
        print
        sys.exit(1)
